/* RoboticsLab, Copyright 2008-2016 Wonik Robotics. All rights reserved.
 *
 * This library is commercial and cannot be redistributed, and/or modified
 * WITHOUT ANY ALLOWANCE OR PERMISSION OF Wonik Robotics.
 */
#ifndef __RDEVICECOMBINEDRIVECMD_H__
#define __RDEVICECOMBINEDRIVECMD_H__

#include <rlab/command/rCmdMobile.h>

#define COMBINEDRIVE_DATAPORT_SET_POSE				(255)
#define COMBINEDRIVE_DATAPORT_SET_VEL_IMMEDIATE		(254)
#define COMBINEDRIVE_DATAPORT_SET_MAXIMUM_VEL		(253)
#define COMBINEDRIVE_DATAPORT_SET_PARAMETER			(252)
#define COMBINEDRIVE_DATAPORT_SET_VEL_TARGET		(0)

#define COMBINEDRIVE_MONITORPORT_POSE					(0)
#define COMBINEDRIVE_MONITORPORT_POSE_LOCAL				(1)
#define COMBINEDRIVE_MONITORPORT_VELOCITY				(2)
#define COMBINEDRIVE_MONITORPORT_VELOCITY_LOCAL			(3)
#define COMBINEDRIVE_MONITORPORT_VELOCITY_LOCAL_WO_SLIP	(4)
#define COMBINEDRIVE_MONITORPORT_SLIP_ANGLE				(5)
#define COMBINEDRIVE_MONITORPORT_WHEEL_VELOCITY			(6)
#define COMBINEDRIVE_MONITORPORT_WHEEL_VELOCITY_WO_SLIP	(7)
#define COMBINEDRIVE_MONITORPORT_TRACTIVE_FORCE			(8)
#define COMBINEDRIVE_MONITORPORT_SINKAGE				(9)
#define COMBINEDRIVE_MONITORPORT_MOTION_RESISTANCE		(10)
#define COMBINEDRIVE_MONITORPORT_PARAMETER				(12)


#endif // __RDEVICECOMBINEDRIVECMD_H__
