/* RoboticsLab, Copyright 2008-2016 Wonik Robotics. All rights reserved.
 *
 * This library is commercial and cannot be redistributed, and/or modified
 * WITHOUT ANY ALLOWANCE OR PERMISSION OF Wonik Robotics.
 */
#ifndef __RDEVICECOMBINEDRIVECMD_H__
#define __RDEVICECOMBINEDRIVECMD_H__

#include <rlab/command/rCmdMobile.h>

#define TRACTORDRIVE_DATAPORT_SET_POSE				(255)
#define TRACTORDRIVE_DATAPORT_SET_VEL_IMMEDIATE		(254)
#define TRACTORDRIVE_DATAPORT_SET_VEL_TARGET		(0)

#define TRACTORDRIVE_MONITORPORT_POSE				(0)
#define TRACTORDRIVE_MONITORPORT_POSE_LOCAL			(1)
#define TRACTORDRIVE_MONITORPORT_VELOCITY			(2)
#define TRACTORDRIVE_MONITORPORT_SLIP_ANGLE			(3)
#define TRACTORDRIVE_MONITORPORT_LATERAL_FORCE		(4)


#endif // __RDEVICECOMBINEDRIVECMD_H__
